### PR TITLE
Update zhCN.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**

### CODE REVIEW

**Comment by nanjuekaien1** [comment]
On the PTR Valdrakken also has a portal to the Emerald Dream Center camp. Coordinates:62.7, 57.4

屏幕截图 2023-11-09 082435

**Comment by nanjuekaien1** [comment]
通往中心营地的传送门

**Comment by Dathwada** [comment]
Thanks for adding the new portal. I didn't know it existed, read it on wowhead today.

**Comment by nanjuekaien1** [comment]
So gracious, need to thank you for writing such a great plugin.

**Comment by Dathwada** [comment]
[Varnzali](https://legacy.curseforge.com/members/varnzali) created this plugin 2017. I took over the development in mid-2019. So the credit for the idea goes to him.

**Comment by nanjuekaien1** [comment]
But thank you very much.

**Pull request merged**
